version: '3.1'

services:
    mysql:
      image: mysql:latest
      container_name: "af2_mysql"
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PWD}
      volumes:
         - ./volumes/mysql/data:/var/lib/mysql
    mongodb:
        image: mongo:latest
        container_name: "af2_mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./volumes/data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --bind_ip_all --logpath=/dev/null
    nginx:
        build:
            context: ./nginx
        container_name: "af2_nginx"
        environment:
            - spring_profiles_active=${spring_profiles_active}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./volumes/www:/var/www
            - ./volumes/root/certs-data/:/data/letsencrypt/
            - ./volumes/etc/letsencrypt/:/etc/letsencrypt/
            - ./volumes/var/docker/nginx/ssl:/etc/nginx/ssl
        links:
            - assets
            - clients
        hostname: web1
        domainname: web1.com
    assets:
        build:
            context: ../af-ms-assets
        container_name: "af2_assets"
        environment:
            - spring.profiles.active=${spring_profiles_active}
            - JAVA_OPTS=-Xm2g -Xms2g -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
        ports:
            - "8000:8000"
            - "8191:8080"
        links:
            - mongodb
        hostname: tomcat
        domainname: ms.springcat.com
    clients:
        build:
            context: ../af-ms-clients
        container_name: "af2_clients"
        environment:
            - spring.profiles.active=${spring_profiles_active}
            - JAVA_OPTS=-Xm2g -Xms2g -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
        ports:
            - "8002:8000"
            - "8193:8080"
        links:
            - mongodb
        hostname: tomcat
        domainname: ms.springcat.com
